version: "3.9"

services:
  db:
    image: postgres:16
    container_name: schedule_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: schedule_user
      POSTGRES_PASSWORD: schedule_pass
      POSTGRES_DB: schedule_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U schedule_user -d schedule_dev" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
